name: Windows EXE Build

on:
  push:
    branches: [ main ]


permissions:
  contents: read
  actions: write

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    permissions:
      contents: read
      actions: write

    env:
     GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean old output directory
        run: if exist output rmdir /s /q output

      - name: Configure project with CMake
        run: cmake -S . -B output -DCMAKE_BUILD_TYPE=Release

      - name: Build the project
        run: cmake --build output --config Release

      - name: Upload EXE as artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: minecraft_server.exe
          path: output/Release/*.exe
          token: ${{ env.GITHUB_TOKEN }}
