name: Windows EXE Build

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  actions: write

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean old output directory
        run: |
          if (Test-Path output) {
            Remove-Item output -Recurse -Force
          }

      - name: Bootstrap vcpkg and install zlib
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
          .\vcpkg\vcpkg.exe install zlib:x64-windows

      - name: Configure project with CMake + vcpkg
        shell: pwsh
        run: |
          $tc = Join-Path $Env:GITHUB_WORKSPACE 'vcpkg\scripts\buildsystems\vcpkg.cmake'
          cmake `
            -DCMAKE_TOOLCHAIN_FILE="$tc" `
            -DVCPKG_TARGET_TRIPLET="x64-windows" `
            -DCMAKE_BUILD_TYPE="Release" `
            -S "$Env:GITHUB_WORKSPACE" `
            -B "$Env:GITHUB_WORKSPACE\output"

      - name: Build the project
        run: cmake --build output --config Release

      - name: Upload EXE as artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftServer.exe
          path: output/Release/*.exe
          token: ${{ env.GITHUB_TOKEN }}
